import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'ja' | 'vi' | 'zh' | 'hi' | 'id' | 'ko' | 'th' | 'ms' | 'fil' | 'bn' | 'ur' | 'ta' | 'te' | 'my';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

// Translation strings
const translations = {
  en: {
    welcome: 'Welcome!',
    settings: 'Settings',
    home: 'Home',
    kyc: 'KYC',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    searchLanguage: 'Search language...',
    step1Title: 'Step 1: Try it',
    step1Text: 'Edit app/(tabs)/index.tsx to see changes.',
    step2Title: 'Step 2: Explore',
    step2Text: "Tap the Explore tab to learn more about what's included in this starter app.",
    step3Title: 'Step 3: Get a fresh start',
    step3Text: "When you're ready, run npm run reset-project to get a fresh app directory.",
    kycTitle: 'KYC Verification',
    kycPlaceholder: 'This page will be updated later.',
    kycDescription: 'Complete your identity verification to access all features',
    kycStartMessage: 'Ready to start your identity verification',
    kycLoading: 'Loading verification...',
    kycInProgress: 'Verification in progress. Complete the process in the opened window.',
    kycCompleted: 'Verification completed successfully!',
    kycFailed: 'Verification failed. Please try again.',
    kycStartButton: 'Start Verification',
    kycContinue: 'Continue Verification',
    kycViewDetails: 'View Details',
    kycRequirements: 'Requirements',
    kycRequirement1: 'Valid government-issued ID',
    kycRequirement2: 'Clear selfie photo',
    kycRequirement3: 'Stable internet connection',
  },
  ja: {
    welcome: 'ようこそ！',
    settings: '設定',
    home: 'ホーム',
    kyc: 'KYC',
    theme: 'テーマ',
    darkMode: 'ダークモード',
    lightMode: 'ライトモード',
    language: '言語',
    searchLanguage: '言語を検索...',
    step1Title: 'ステップ1: 試してみる',
    step1Text: 'app/(tabs)/index.tsxを編集して変更を確認してください。',
    step2Title: 'ステップ2: 探索する',
    step2Text: 'Exploreタブをタップして、このスターターアプリに含まれているものを確認してください。',
    step3Title: 'ステップ3: 新しいスタート',
    step3Text: '準備ができたら、npm run reset-projectを実行して新しいアプリディレクトリを取得してください。',
    kycTitle: 'KYC認証',
    kycPlaceholder: 'このページは後で更新されます。',
    kycDescription: 'すべての機能にアクセスするために本人確認を完了してください',
    kycStartMessage: '本人確認を開始する準備ができました',
    kycLoading: '認証を読み込んでいます...',
    kycInProgress: '認証が進行中です。開いたウィンドウでプロセスを完了してください。',
    kycCompleted: '認証が正常に完了しました！',
    kycFailed: '認証に失敗しました。もう一度お試しください。',
    kycStartButton: '認証を開始',
    kycContinue: '認証を続ける',
    kycViewDetails: '詳細を表示',
    kycRequirements: '必要なもの',
    kycRequirement1: '有効な政府発行の身分証明書',
    kycRequirement2: '鮮明な自撮り写真',
    kycRequirement3: '安定したインターネット接続',
  },
  vi: {
    welcome: 'Chào mừng!',
    settings: 'Cài đặt',
    home: 'Trang chủ',
    kyc: 'KYC',
    theme: 'Giao diện',
    darkMode: 'Chế độ tối',
    lightMode: 'Chế độ sáng',
    language: 'Ngôn ngữ',
    searchLanguage: 'Tìm kiếm ngôn ngữ...',
    step1Title: 'Bước 1: Thử nghiệm',
    step1Text: 'Chỉnh sửa app/(tabs)/index.tsx để xem thay đổi.',
    step2Title: 'Bước 2: Khám phá',
    step2Text: 'Nhấn tab Explore để tìm hiểu thêm về những gì có trong ứng dụng khởi đầu này.',
    step3Title: 'Bước 3: Bắt đầu mới',
    step3Text: 'Khi bạn sẵn sàng, chạy npm run reset-project để có thư mục ứng dụng mới.',
    kycTitle: 'Xác thực KYC',
    kycPlaceholder: 'Trang này sẽ được cập nhật sau.',
    kycDescription: 'Hoàn thành xác thực danh tính để truy cập tất cả tính năng',
    kycStartMessage: 'Sẵn sàng bắt đầu xác thực danh tính của bạn',
    kycLoading: 'Đang tải xác thực...',
    kycInProgress: 'Xác thực đang tiến hành. Hoàn thành quy trình trong cửa sổ đã mở.',
    kycCompleted: 'Xác thực hoàn tất thành công!',
    kycFailed: 'Xác thực thất bại. Vui lòng thử lại.',
    kycStartButton: 'Bắt đầu xác thực',
    kycContinue: 'Tiếp tục xác thực',
    kycViewDetails: 'Xem chi tiết',
    kycRequirements: 'Yêu cầu',
    kycRequirement1: 'Giấy tờ tùy thân hợp lệ do chính phủ cấp',
    kycRequirement2: 'Ảnh selfie rõ ràng',
    kycRequirement3: 'Kết nối internet ổn định',
  },
  zh: {
    welcome: '欢迎！',
    settings: '设置',
    home: '主页',
    kyc: 'KYC',
    theme: '主题',
    darkMode: '深色模式',
    lightMode: '浅色模式',
    language: '语言',
    searchLanguage: '搜索语言...',
    step1Title: '第1步：尝试',
    step1Text: '编辑 app/(tabs)/index.tsx 查看更改。',
    step2Title: '第2步：探索',
    step2Text: '点击探索标签了解更多关于此入门应用程序的内容。',
    step3Title: '第3步：重新开始',
    step3Text: '准备好后，运行 npm run reset-project 获取新的应用程序目录。',
    kycTitle: 'KYC认证',
    kycPlaceholder: '此页面稍后更新。',
    kycDescription: '完成身份验证以访问所有功能',
    kycStartMessage: '准备开始您的身份验证',
    kycLoading: '正在加载验证...',
    kycInProgress: '验证正在进行中。请在打开的窗口中完成流程。',
    kycCompleted: '验证成功完成！',
    kycFailed: '验证失败。请重试。',
    kycStartButton: '开始验证',
    kycContinue: '继续验证',
    kycViewDetails: '查看详情',
    kycRequirements: '要求',
    kycRequirement1: '有效的政府颁发的身份证件',
    kycRequirement2: '清晰的自拍照',
    kycRequirement3: '稳定的网络连接',
  },
  hi: {
    welcome: 'स्वागत है!',
    settings: 'सेटिंग्स',
    home: 'होम',
    kyc: 'KYC',
    theme: 'थीम',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    language: 'भाषा',
    searchLanguage: 'भाषा खोजें...',
    step1Title: 'चरण 1: इसे आज़माएं',
    step1Text: 'परिवर्तन देखने के लिए app/(tabs)/index.tsx संपादित करें।',
    step2Title: 'चरण 2: एक्सप्लोर करें',
    step2Text: 'इस स्टार्टर ऐप में क्या शामिल है, यह जानने के लिए एक्सप्लोर टैब टैप करें।',
    step3Title: 'चरण 3: नई शुरुआत करें',
    step3Text: 'जब आप तैयार हों, तो नई ऐप डायरेक्टरी पाने के लिए npm run reset-project चलाएं।',
    kycTitle: 'KYC',
    kycPlaceholder: 'यह पेज बाद में अपडेट किया जाएगा।',
    kycDescription: 'Complete your identity verification to access all features',
    kycStartMessage: 'Ready to start your identity verification',
    kycLoading: 'Loading verification...',
    kycInProgress: 'Verification in progress. Complete the process in the opened window.',
    kycCompleted: 'Verification completed successfully!',
    kycFailed: 'Verification failed. Please try again.',
    kycStartButton: 'Start Verification',
    kycContinue: 'Continue Verification',
    kycViewDetails: 'View Details',
    kycRequirements: 'Requirements',
    kycRequirement1: 'Valid government-issued ID',
    kycRequirement2: 'Clear selfie photo',
    kycRequirement3: 'Stable internet connection',
  },
  id: {
    welcome: 'Selamat datang!',
    settings: 'Pengaturan',
    home: 'Beranda',
    kyc: 'KYC',
    theme: 'Tema',
    darkMode: 'Mode Gelap',
    lightMode: 'Mode Terang',
    language: 'Bahasa',
    searchLanguage: 'Cari bahasa...',
    step1Title: 'Langkah 1: Coba',
    step1Text: 'Edit app/(tabs)/index.tsx untuk melihat perubahan.',
    step2Title: 'Langkah 2: Jelajahi',
    step2Text: 'Ketuk tab Explore untuk mempelajari lebih lanjut tentang apa yang disertakan dalam aplikasi starter ini.',
    step3Title: 'Langkah 3: Mulai baru',
    step3Text: 'Saat Anda siap, jalankan npm run reset-project untuk mendapatkan direktori aplikasi baru.',
    kycTitle: 'KYC',
    kycPlaceholder: 'Halaman ini akan diperbarui nanti.',
    kycDescription: 'Complete your identity verification to access all features',
    kycStartMessage: 'Ready to start your identity verification',
    kycLoading: 'Loading verification...',
    kycInProgress: 'Verification in progress. Complete the process in the opened window.',
    kycCompleted: 'Verification completed successfully!',
    kycFailed: 'Verification failed. Please try again.',
    kycStartButton: 'Start Verification',
    kycContinue: 'Continue Verification',
    kycViewDetails: 'View Details',
    kycRequirements: 'Requirements',
    kycRequirement1: 'Valid government-issued ID',
    kycRequirement2: 'Clear selfie photo',
    kycRequirement3: 'Stable internet connection',
  },
  ko: {
    welcome: '환영합니다!',
    settings: '설정',
    home: '홈',
    kyc: 'KYC',
    theme: '테마',
    darkMode: '다크 모드',
    lightMode: '라이트 모드',
    language: '언어',
    searchLanguage: '언어 검색...',
    step1Title: '1단계: 시도해보기',
    step1Text: '변경 사항을 보려면 app/(tabs)/index.tsx를 편집하세요.',
    step2Title: '2단계: 탐색하기',
    step2Text: '이 스타터 앱에 포함된 내용을 알아보려면 탐색 탭을 탭하세요.',
    step3Title: '3단계: 새로 시작하기',
    step3Text: '준비가 되면 npm run reset-project를 실행하여 새 앱 디렉토리를 얻으세요.',
    kycTitle: 'KYC',
    kycPlaceholder: '이 페이지는 나중에 업데이트됩니다.',
    kycDescription: 'Complete your identity verification to access all features',
    kycStartMessage: 'Ready to start your identity verification',
    kycLoading: 'Loading verification...',
    kycInProgress: 'Verification in progress. Complete the process in the opened window.',
    kycCompleted: 'Verification completed successfully!',
    kycFailed: 'Verification failed. Please try again.',
    kycStartButton: 'Start Verification',
    kycContinue: 'Continue Verification',
    kycViewDetails: 'View Details',
    kycRequirements: 'Requirements',
    kycRequirement1: 'Valid government-issued ID',
    kycRequirement2: 'Clear selfie photo',
    kycRequirement3: 'Stable internet connection',
  },
  th: {
    welcome: 'ยินดีต้อนรับ!',
    settings: 'การตั้งค่า',
    home: 'หน้าแรก',
    kyc: 'KYC',
    theme: 'ธีม',
    darkMode: 'โหมดมืด',
    lightMode: 'โหมดสว่าง',
    language: 'ภาษา',
    searchLanguage: 'ค้นหาภาษา...',
    step1Title: 'ขั้นตอนที่ 1: ลองใช้',
    step1Text: 'แก้ไข app/(tabs)/index.tsx เพื่อดูการเปลี่ยนแปลง',
    step2Title: 'ขั้นตอนที่ 2: สำรวจ',
    step2Text: 'แตะแท็บ Explore เพื่อเรียนรู้เพิ่มเติมเกี่ยวกับสิ่งที่รวมอยู่ในแอปเริ่มต้นนี้',
    step3Title: 'ขั้นตอนที่ 3: เริ่มต้นใหม่',
    step3Text: 'เมื่อคุณพร้อม ให้รัน npm run reset-project เพื่อรับไดเรกทอรีแอปใหม่',
    kycTitle: 'KYC',
    kycPlaceholder: 'หน้านี้จะอัปเดตในภายหลัง',
    kycDescription: 'Complete your identity verification to access all features',
    kycStartMessage: 'Ready to start your identity verification',
    kycLoading: 'Loading verification...',
    kycInProgress: 'Verification in progress. Complete the process in the opened window.',
    kycCompleted: 'Verification completed successfully!',
    kycFailed: 'Verification failed. Please try again.',
    kycStartButton: 'Start Verification',
    kycContinue: 'Continue Verification',
    kycViewDetails: 'View Details',
    kycRequirements: 'Requirements',
    kycRequirement1: 'Valid government-issued ID',
    kycRequirement2: 'Clear selfie photo',
    kycRequirement3: 'Stable internet connection',
  },
  ms: {
    welcome: 'Selamat datang!',
    settings: 'Tetapan',
    home: 'Laman Utama',
    kyc: 'KYC',
    theme: 'Tema',
    darkMode: 'Mod Gelap',
    lightMode: 'Mod Cerah',
    language: 'Bahasa',
    searchLanguage: 'Cari bahasa...',
    step1Title: 'Langkah 1: Cuba',
    step1Text: 'Edit app/(tabs)/index.tsx untuk melihat perubahan.',
    step2Title: 'Langkah 2: Terokai',
    step2Text: 'Ketik tab Explore untuk mengetahui lebih lanjut tentang apa yang disertakan dalam aplikasi permulaan ini.',
    step3Title: 'Langkah 3: Mula semula',
    step3Text: 'Apabila anda bersedia, jalankan npm run reset-project untuk mendapatkan direktori aplikasi baru.',
    kycTitle: 'KYC',
    kycPlaceholder: 'Halaman ini akan dikemas kini kemudian.',
    kycDescription: 'Complete your identity verification to access all features',
    kycStartMessage: 'Ready to start your identity verification',
    kycLoading: 'Loading verification...',
    kycInProgress: 'Verification in progress. Complete the process in the opened window.',
    kycCompleted: 'Verification completed successfully!',
    kycFailed: 'Verification failed. Please try again.',
    kycStartButton: 'Start Verification',
    kycContinue: 'Continue Verification',
    kycViewDetails: 'View Details',
    kycRequirements: 'Requirements',
    kycRequirement1: 'Valid government-issued ID',
    kycRequirement2: 'Clear selfie photo',
    kycRequirement3: 'Stable internet connection',
  },
  fil: {
    welcome: 'Maligayang pagdating!',
    settings: 'Mga Setting',
    home: 'Home',
    kyc: 'KYC',
    theme: 'Tema',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Wika',
    searchLanguage: 'Maghanap ng wika...',
    step1Title: 'Hakbang 1: Subukan ito',
    step1Text: 'I-edit ang app/(tabs)/index.tsx para makita ang mga pagbabago.',
    step2Title: 'Hakbang 2: Tuklasin',
    step2Text: 'I-tap ang Explore tab para malaman ang tungkol sa kung ano ang kasama sa starter app na ito.',
    step3Title: 'Hakbang 3: Magsimula muli',
    step3Text: 'Kapag handa ka na, patakbuhin ang npm run reset-project para makakuha ng bagong app directory.',
    kycTitle: 'KYC',
    kycPlaceholder: 'Ito ay i-update sa susunod.',
    kycDescription: 'Complete your identity verification to access all features',
    kycStartMessage: 'Ready to start your identity verification',
    kycLoading: 'Loading verification...',
    kycInProgress: 'Verification in progress. Complete the process in the opened window.',
    kycCompleted: 'Verification completed successfully!',
    kycFailed: 'Verification failed. Please try again.',
    kycStartButton: 'Start Verification',
    kycContinue: 'Continue Verification',
    kycViewDetails: 'View Details',
    kycRequirements: 'Requirements',
    kycRequirement1: 'Valid government-issued ID',
    kycRequirement2: 'Clear selfie photo',
    kycRequirement3: 'Stable internet connection',
  },
  bn: {
    welcome: 'স্বাগতম!',
    settings: 'সেটিংস',
    home: 'হোম',
    kyc: 'KYC',
    theme: 'থিম',
    darkMode: 'ডার্ক মোড',
    lightMode: 'লাইট মোড',
    language: 'ভাষা',
    searchLanguage: 'ভাষা অনুসন্ধান করুন...',
    step1Title: 'ধাপ ১: চেষ্টা করুন',
    step1Text: 'পরিবর্তন দেখতে app/(tabs)/index.tsx সম্পাদনা করুন।',
    step2Title: 'ধাপ ২: অন্বেষণ করুন',
    step2Text: 'এই স্টার্টার অ্যাপে কী অন্তর্ভুক্ত আছে তা জানতে এক্সপ্লোর ট্যাব ট্যাপ করুন।',
    step3Title: 'ধাপ ৩: নতুন শুরু করুন',
    step3Text: 'আপনি প্রস্তুত হলে, নতুন অ্যাপ ডিরেক্টরি পেতে npm run reset-project চালান।',
    kycTitle: 'KYC',
    kycPlaceholder: 'এই পৃষ্ঠাটি পরে আপডেট করা হবে।',
    kycDescription: 'Complete your identity verification to access all features',
    kycStartMessage: 'Ready to start your identity verification',
    kycLoading: 'Loading verification...',
    kycInProgress: 'Verification in progress. Complete the process in the opened window.',
    kycCompleted: 'Verification completed successfully!',
    kycFailed: 'Verification failed. Please try again.',
    kycStartButton: 'Start Verification',
    kycContinue: 'Continue Verification',
    kycViewDetails: 'View Details',
    kycRequirements: 'Requirements',
    kycRequirement1: 'Valid government-issued ID',
    kycRequirement2: 'Clear selfie photo',
    kycRequirement3: 'Stable internet connection',
  },
  ur: {
    welcome: 'خوش آمدید!',
    settings: 'ترتیبات',
    home: 'ہوم',
    kyc: 'KYC',
    theme: 'تھیم',
    darkMode: 'ڈارک موڈ',
    lightMode: 'لائٹ موڈ',
    language: 'زبان',
    searchLanguage: 'زبان تلاش کریں...',
    step1Title: 'مرحلہ 1: آزمائیں',
    step1Text: 'تبدیلیاں دیکھنے کے لیے app/(tabs)/index.tsx میں ترمیم کریں۔',
    step2Title: 'مرحلہ 2: تلاش کریں',
    step2Text: 'اس اسٹارٹر ایپ میں کیا شامل ہے یہ جاننے کے لیے Explore ٹیب پر ٹیپ کریں۔',
    step3Title: 'مرحلہ 3: نئی شروعات کریں',
    step3Text: 'جب آپ تیار ہوں تو نئی ایپ ڈائرکٹری حاصل کرنے کے لیے npm run reset-project چلائیں۔',
    kycTitle: 'KYC',
    kycPlaceholder: 'یہ صفحہ بعد میں اپ ڈیٹ کیا جائے گا۔',
    kycDescription: 'Complete your identity verification to access all features',
    kycStartMessage: 'Ready to start your identity verification',
    kycLoading: 'Loading verification...',
    kycInProgress: 'Verification in progress. Complete the process in the opened window.',
    kycCompleted: 'Verification completed successfully!',
    kycFailed: 'Verification failed. Please try again.',
    kycStartButton: 'Start Verification',
    kycContinue: 'Continue Verification',
    kycViewDetails: 'View Details',
    kycRequirements: 'Requirements',
    kycRequirement1: 'Valid government-issued ID',
    kycRequirement2: 'Clear selfie photo',
    kycRequirement3: 'Stable internet connection',
  },
  ta: {
    welcome: 'வரவேற்கிறோம்!',
    settings: 'அமைப்புகள்',
    home: 'முகப்பு',
    kyc: 'KYC',
    theme: 'தீம்',
    darkMode: 'இருண்ட பயன்முறை',
    lightMode: 'ஒளி பயன்முறை',
    language: 'மொழி',
    searchLanguage: 'மொழியைத் தேடு...',
    step1Title: 'படி 1: முயற்சிக்கவும்',
    step1Text: 'மாற்றங்களைக் காண app/(tabs)/index.tsx ஐ திருத்தவும்.',
    step2Title: 'படி 2: ஆராயுங்கள்',
    step2Text: 'இந்த ஸ்டார்ட்டர் ஆப்பில் என்ன சேர்க்கப்பட்டுள்ளது என்பதை அறிய Explore டேப்பை தட்டவும்.',
    step3Title: 'படி 3: புதிதாக தொடங்கவும்',
    step3Text: 'நீங்கள் தயாராக இருக்கும்போது, புதிய ஆப் கோப்பகத்தைப் பெற npm run reset-project ஐ இயக்கவும்.',
    kycTitle: 'KYC',
    kycPlaceholder: 'இந்தப் பக்கம் பின்னர் புதுப்பிக்கப்படும்.',
    kycDescription: 'Complete your identity verification to access all features',
    kycStartMessage: 'Ready to start your identity verification',
    kycLoading: 'Loading verification...',
    kycInProgress: 'Verification in progress. Complete the process in the opened window.',
    kycCompleted: 'Verification completed successfully!',
    kycFailed: 'Verification failed. Please try again.',
    kycStartButton: 'Start Verification',
    kycContinue: 'Continue Verification',
    kycViewDetails: 'View Details',
    kycRequirements: 'Requirements',
    kycRequirement1: 'Valid government-issued ID',
    kycRequirement2: 'Clear selfie photo',
    kycRequirement3: 'Stable internet connection',
  },
  te: {
    welcome: 'స్వాగతం!',
    settings: 'సెట్టింగ్‌లు',
    home: 'హోమ్',
    kyc: 'KYC',
    theme: 'థీమ్',
    darkMode: 'డార్క్ మోడ్',
    lightMode: 'లైట్ మోడ్',
    language: 'భాష',
    searchLanguage: 'భాషను వెతకండి...',
    step1Title: 'దశ 1: ప్రయత్నించండి',
    step1Text: 'మార్పులను చూడటానికి app/(tabs)/index.tsx ని సవరించండి.',
    step2Title: 'దశ 2: అన్వేషించండి',
    step2Text: 'ఈ స్టార్టర్ యాప్‌లో ఏమి ఉందో తెలుసుకోవడానికి Explore ట్యాబ్‌ను నొక్కండి.',
    step3Title: 'దశ 3: కొత్తగా ప్రారంభించండి',
    step3Text: 'మీరు సిద్ధంగా ఉన్నప్పుడు, కొత్త యాప్ డైరెక్టరీని పొందడానికి npm run reset-project ని రన్ చేయండి.',
    kycTitle: 'KYC',
    kycPlaceholder: 'ఈ పేజీ తర్వాత నవీకరించబడుతుంది.',
    kycDescription: 'Complete your identity verification to access all features',
    kycStartMessage: 'Ready to start your identity verification',
    kycLoading: 'Loading verification...',
    kycInProgress: 'Verification in progress. Complete the process in the opened window.',
    kycCompleted: 'Verification completed successfully!',
    kycFailed: 'Verification failed. Please try again.',
    kycStartButton: 'Start Verification',
    kycContinue: 'Continue Verification',
    kycViewDetails: 'View Details',
    kycRequirements: 'Requirements',
    kycRequirement1: 'Valid government-issued ID',
    kycRequirement2: 'Clear selfie photo',
    kycRequirement3: 'Stable internet connection',
  },
  my: {
    welcome: 'ကြိုဆိုပါတယ်!',
    settings: 'ဆက်တင်များ',
    home: 'ပင်မ',
    kyc: 'KYC',
    theme: 'အပြင်အဆင်',
    darkMode: 'အမှောင်မုဒ်',
    lightMode: 'အလင်းမုဒ်',
    language: 'ဘာသာစကား',
    searchLanguage: 'ဘာသာစကားရှာဖွေရန်...',
    step1Title: 'အဆင့် ၁: စမ်းကြည့်ပါ',
    step1Text: 'ပြောင်းလဲမှုများကိုကြည့်ရန် app/(tabs)/index.tsx ကို တည်းဖြတ်ပါ။',
    step2Title: 'အဆင့် ၂: စူးစမ်းလေ့လာပါ',
    step2Text: 'ဤစတင်အက်ပ်တွင် ဘာများပါဝင်သည်ကို လေ့လာရန် Explore တက်ဘ်ကို နှိပ်ပါ။',
    step3Title: 'အဆင့် ၃: အသစ်စတင်ပါ',
    step3Text: 'သင်အဆင်သင့်ဖြစ်သောအခါ အက်ပ်လမ်းကြောင်းအသစ်ရရန် npm run reset-project ကို လုပ်ဆောင်ပါ။',
    kycTitle: 'KYC',
    kycPlaceholder: 'ဤစာမျက်နှာကို နောက်မှ အပ်ဒိတ်လုပ်ပါမည်။',
    kycDescription: 'Complete your identity verification to access all features',
    kycStartMessage: 'Ready to start your identity verification',
    kycLoading: 'Loading verification...',
    kycInProgress: 'Verification in progress. Complete the process in the opened window.',
    kycCompleted: 'Verification completed successfully!',
    kycFailed: 'Verification failed. Please try again.',
    kycStartButton: 'Start Verification',
    kycContinue: 'Continue Verification',
    kycViewDetails: 'View Details',
    kycRequirements: 'Requirements',
    kycRequirement1: 'Valid government-issued ID',
    kycRequirement2: 'Clear selfie photo',
    kycRequirement3: 'Stable internet connection',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  
  // Load saved language preference
  useEffect(() => {
    AsyncStorage.getItem('language').then((savedLanguage) => {
      if (savedLanguage && ['en', 'ja', 'vi', 'zh', 'hi', 'id', 'ko', 'th', 'ms', 'fil', 'bn', 'ur', 'ta', 'te', 'my'].includes(savedLanguage)) {
        setLanguageState(savedLanguage as Language);
      }
    });
  }, []);

  const setLanguage = async (newLanguage: Language) => {
    setLanguageState(newLanguage);
    await AsyncStorage.setItem('language', newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}